### ISSUE TITLE
Compiler does not report the size of the sketch in Arduino IDE

### ISSUE THREAD

**Issue by ShaggyDog18** [WeActStudio/ArduinoCore-AT32F4#10]
Compiling my sketch in Arduino IDE 2.0.0-rc9.2 and get the following for successful compilation:
_Sketch uses 0 bytes (0%) of program storage space. Maximum is 1048576 bytes._

However, the build .hex file size is 30KB and .elf size is 474KB

**Comment by WeActStudio** [comment]
Fix
