### ISSUE TITLE
Availability of all six/seven Serials (UARTs) in HardwareSerial

### ISSUE THREAD

**Issue by ShaggyDog18** [WeActStudio/ArduinoCore-AT32F4#8]
Please, deploy all 6 Serials (UART) to HardwareSerial soon. 
I need five (5) Serial interfaces for my project; however, reviewing HardwareSerial files I have discovered that Seial1, 2 and 3 are deployed so far. Please, include Serial 4 and 5 soon. 
Ideally, if you make all 6/7 Serials available.
Thank you!

**Comment by WeActStudio** [comment]
Already add uart4(PA0-TX, PA1-RX) and uart5 (PB9-TX, PB8-RX)

**Comment by ShaggyDog18** [comment]
Could you please, add UART6 to the HardwareSerial!
My project is successful and I am extending functionality, now need one more HW UART. Please, add UART6.
I appreciate your support very much! Thank you!
